No
CSUA/csua-backend pull request #134
Opened 2021-05-05 08:22 UTC by michaelzhiluo

2021-05-05 08:25 UTC, robertquitt requested changes

2021-05-05 08:25 UTC, robertquitt commented on apps/discordbot/bot.py
> -            )
```suggestion
        if "!cope" in msg:
            await message.channel.send(
                "https://cdn.discordapp.com/attachments/785419328131563530/836033002500522024/michael_cope.mp4"
            )
```

2021-05-05 09:32 UTC, robertquitt requested changes
!cope

2021-05-08 04:40 UTC, michaelzhiluo commented
!cope

2021-05-08 04:42 UTC, rnithin1 commented
é

2021-05-08 04:42 UTC, merged

2021-05-08 04:43 UTC, kuhusharma commented
!cope :D